### ISSUE TITLE
Alighnment flub in bump allocator, 0.2.0

### ISSUE THREAD

**Issue by blt** [blt/bh_alloc#2]
As noted by @simonsapin the alignment is off in the allocater as of 0.2.0. Full run-down [here](https://github.com/blt/bh_alloc/pull/1#issuecomment-435846699).

**Comment by Amanieu** [comment]
This is causing failures when testing `hashbrown` since it uses SSE instruction which require 16-byte alignment.

**Comment by blt** [comment]
@Amanieu I've just pushed #3 which _should_ be on the road to addressing this issue. I'll add a bin target to this project that makes use of hashbrown.

**Comment by blt** [comment]
@Amanieu 87584c2 introduces a hashbrown integration test which fails at present.
